### ISSUE TITLE
Přidání odkazu na stránku http://www.maskola.cz/cz-informace-pro-tridy

### ISSUE THREAD

**Issue by HonzaaD** [jpachta/UcimeSeDoMaSkola#9]
Super rozlišení a moc za něho děkuji. Dalo by se ještě přidat do rozlišení přímo odkaz na stránku http://www.maskola.cz/cz-informace-pro-tridy abych prostě rozlišení mohl používat místo záložky? A dostal se hned na správnou stránku s úkoly?

**Comment by jpachta** [comment]
Hm, teď trochu nerozumím, kde by se ten odkaz měl projevit. Mužes to trochu rozvést, kde a jak.

**Comment by HonzaaD** [comment]
No teď když kliknu a ikonu doplňku, tak se mi zobrazí toto menu, kde první položka je odkaz na tuto stránku https://github.com/jpachta/UcimeSeDoMaSkola/ a já si myslím, že by bylo super, kdyby tam byl nad tím i druhý odkaz, který by odkazoval přímo na stránku http://www.maskola.cz/cz-informace-pro-tridy 

![plugin máškola](https://user-images.githubusercontent.com/12045527/80384522-4497c580-88a5-11ea-9de2-70d9b7888f24.png)

**Comment by jpachta** [comment]
Jasně, chápu. Odkaz přidám v nové verzi rozšíření, snad ještě tento týden.

**Comment by jpachta** [comment]
Ahoj, tak jsem pridal menu s odkazem na stranky skoly/informace pro tridy/github homepage. Verze 2.4.1 uz je nahrana na i na WebStore.

**Comment by HonzaaD** [comment]
Super děkuji moc..
